### ISSUE TITLE
Consider adding DOES support

### ISSUE THREAD

**Issue by stevan** [stevan/p5-UNIVERSAL-Object#4]
If `MOP` is loaded in the `%INC` we can add in `MOP::Role` support, but if not we could just let it default to `UNIVERSAL::DOES` version.

**Comment by tabulon** [comment]
Hi Stevan,

Adding support for `DOES()` (based on the simple `@DOES` convention) would be great. 

However, instead of realying on `MOP`, please consider the other way around, i.e. : moving the code that's needed to implement `DOES()` into `UNIVERSAL::Object`;

Or better yet, an independent module, which may ease the adoption of the `@DOES` convention.

Reasoning: 

1) `MOP` already depends on `UNIVERSAL::Object` (currently, meta-classes are implemented as `UNIVERSAL::Object`)
2) `MOP` is heavier and currently has more dependencies
3) The convention that uses a `@DOES` array seems to be quite a nice one (that other role toolsets, like `Role::Tiny` may also adopt somewhere down the road)
4) It's also quite simple to implement on its own. Not a lot of code. No extra dependencies needed.

BTW: currently, `MOP::Role::does_role()` _only_ walks up `@DOES`, without any interplay with `@ISA`; probably by design.
`Moxie::Object` seems to handle this correctly... `MOP::Class` should probably override `does_role()` in any case.

**Comment by stevan** [comment]
Hey @tabulon 

My original thinking was that `UNIVERSAL::Object` should not know about roles, since roles are not a core Perl feature. It felt unbalanced to include one aspect for testing role membership (`DOES()`), but not include the other aspects that implement composing of roles (`@DOES` and `MOP::Util:: compose_roles()`). 

The simplicity of `UNIVERSAL::Object` depends on some assumptions being true, like being able to rely on the behavior and usage of `@ISA` which is reasonable since it is a core feature. In order to add `DOES()` support without also adding the features to compose roles, etc. I would need to be able to rely on the behavior and usage of `@DOES` in the same way, and that is not possible since it is not a core feature.   

At some point I probably considered the idea of pulling the full role implementation out of the `MOP` and moving it into `UNIVERSAL::Object` or into its own independent model, both free from `MOP`, but if you look at the implementation, it doesn't make a lot of sense. 

I will try to address each of your reasons.

1. While `MOP` does depend on `UNIVERSAL::Object`, just lifting the role handling code from `MOP` to `UNIVERSAL::Object` is not so simple. 
    - I use the `MOP::Role` meta object quite heavily in `MOP::Util:: compose_roles()`, specifically in the parts that handle role method composition and role method requirements. 
    - The code/concepts which drives role method composition is the code which determines method membership in a package, and the code/concepts which drive role method requirements is the code which determines if a method is abstract (subroutine with no body). 
    - The above code/concepts are implemented entirely within `MOP` and splitting them out of `MOP` is not really possible without a lot of code duplication and would result in a fracturing of the concepts between `MOP` and `UNIVERSAL::Object`. 
2. Honestly, I don't think that `MOP` really has many dependencies, aside from `UNIVERSAL::Object`, the are only two which are non-core (`Devel::Hook` and `Devel::OverloadInfo`), neither of which have many (non-core) dependencies themselves. Another thing to note is that most all of the dependencies are *only* used inside `MOP::Internal::Util` and it was my intention to (eventually) re-write this module in XS and remove all those dependencies. 
3. The `@DOES` convention is a very surface feature of roles, and maybe it would be nice if other modules (`Role::Tiny`) used it, but just using `@DOES` will not mean role implementations are compatible at all. Role composition via `MOP` is built upon several other concepts/features which are specific to `MOP`, such as:
    - the `%HAS` variable used to store slot information (most of the non-Moo(se) role modules have no concept of slots)
    - the idea that `sub foo;` is a required method 
    - the specifics of method membership in a package 
4. While the code itself might be simple, it depends upon adherence to concepts/conventions which are inherent to the `MOP` module and the implementation of those concepts/conventions is done using the aforementioned dependencies. 

As for the interplay with `@ISA`, I never really agreed with that idea, `Moxie::Object` was probably just a moment of weakness. Also `Moxie` should probably be ignored for now, all the nice bits were moved out into the `UNIVERSAL::Object` and `MOP` modules, along with the `slots` and `roles` pragmas. 

And lastly, it was always my intention to build a layer on top of `UNIVERSAL::Object` and `MOP` that would make this a moot point. The `roles` and `slots` pragmas are an extremely minimalist version of this. 

Hope this explains some of my thinking, feel free to poke and ask questions if things aren't clear.

**Comment by tabulon** [comment]
Hi Stevan,

Thanks a lot for your reply. It's very pleasant to see that your interest in `UNIVERSAL::Object` and friends (`MOP` / `slots` / `roles`) is still kicking. 

I love the overall simplicity of all this and especially the "back to the basics" approach (e.g. reliance on native Perl features and package symbols, like `*HAS` and `*DOES`).

Also, the code itself is slim, clean and quite easy to follow : so it's relatively straightforward to understand *what* is going on and *how* it is being done.

Grasping the *why* behind some of the choices is another game though and that's where an explanation is quite helpful.

So thank you for sharing your thinking behind this one.

I am not sure that I agree with some of the given reasons, but I prefer abstaining from dwelling into a long discussion at least until I get a better understanding of some of the other thinking around `UNIVERSAL::Object`, `MOP` and the `slots` / `roles` pragmas. 

So far, apart from some older slides/talks that touch upon the journey, below are the only directly related background material I have been able to find :

- ["Hold My Beer and Watch This!"](https://www.youtube.com/watch?v=w5U7eoeuO90), TPC 2017, D.C.

- ["UNIVERSAL::Object – All your base class are belong to us"](https://www.youtube.com/watch?v=lnleCcKqcv4), TPC 2018 Utah
- ["Gazing into the Camel's navel"](https://www.youtube.com/watch?v=ugEry1UWg84), TPC 2018 Utah


Is there any other directly related background material that I can go through before asking some (possibly stupid) questions (mostly in the *why* department) or making some suggestions (mostly around behavior/semantics/conventions) ? 

Also, where would be a good place to ask? -- maybe go ahead and open a few issues (some being fake ones) on the corresponding repos?

### Interplay with `isa()` or `@ISA`

Just to make sure I understand your side note correctly: 

When you say you never really agreed with the idea (of `DOES` having an interplay with `@ISA`), I hope you aren't suggesting, at this point in time, a narrower semantics  than what has been documented for [UNIVERSAL::DOES()](https://perldoc.perl.org/UNIVERSAL#CLASS-%3EDOES(-ROLE-)) all these years ?

i.e. the equivalent of removing the following line:

```perl
sub DOES {
...
    return 1 if $class->isa( $role );
...
    # UPDATE: The below is the @ISA interplay we are talking about. Where was my head when wrote the above?
    return 1 if scalar grep { MOP::Util::get_meta( $_ )->does_role( $role ) } @{ $meta->mro };
...
}
```

If so, it would be quite troublesome... 

BTW, `Moose` currently conforms to this. So does the `roles` pragma, whose code for `DOES()` is almost the same as that of `Moxie::Object`, the only difference being the way in which `$meta` is instantiated. So, you still have the above line. 

So I have probably misunderstood your comment, which would make this the first stupid question :-) But still wanted to make sure...
