### ISSUE TITLE
sort keys when populating hashref

### ISSUE THREAD

**Issue by tobyink** [stevan/p5-UNIVERSAL-Object#6]
This line here:
https://github.com/stevan/p5-UNIVERSAL-Object/blob/master/lib/UNIVERSAL/Object.pm#L64

Otherwise, if you've got a class with multiple required attributes, it's unpredictable what exception will be thrown.

```
package Foo;
use parent qw(UNIVERSAL::Object);
our %HAS = (
  bar => sub { die 'bar required' },
  baz => sub { die 'baz required' },
);
__PACKAGE__->new;
```

**Comment by stevan** [comment]
That is annoying, but kind of expected for HASH based instances, don't you think? 

How does Moo/Moose handle this?

**Comment by tobyink** [comment]
Method::Generate::Constructor (part of Moo) uses this to generate the part of the constructor which copies attribute values from the constructor arguments to `$new`. As you can see, it sorts the keys.

```
  join '', map {
    my $arg = $test{$_};
    my $arg_key = quotify($arg);
    my $test = defined $arg ? "exists \$args->{$arg_key}" : undef;
    my $source = defined $arg ? "\$args->{$arg_key}" : undef;
    my $attr_spec = $spec->{$_};
    $self->_cap_call($ag->generate_populate_set(
      '$new', $_, $attr_spec, $source, $test, $arg,
    ));
  } sort keys %test;
```

And Class::MOP::Class uses the following, which again sorts by name.

```
sub _inline_slot_initializers {
    my $self = shift;

    my $idx = 0;

    return map { $self->_inline_slot_initializer($_, $idx++) }
               sort { $a->name cmp $b->name } $self->get_all_attributes;
}
```

**Comment by stevan** [comment]
Okay, fair enough.
